name: "Deploy Now: Deploy to IONOS"

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

concurrency: ${{ github.ref }}

jobs:
  deploy-to-ionos:
    runs-on: ubuntu-latest
    steps:
      - name: Planner check
        run: echo "IONOS deploy workflow planner check for ${{ inputs.version }}"
